version = 1

test_patterns = [".py"]

exclude_patterns = [
    ".vscode/",
    "secret/",
    "src/",
    ".gitignore",
    "README.md"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"